# Site

title: Web Services and APIs with Python
handouts:
 - worksheet.ipynb
tag: v0.0
lesson: 8
instructor: Ian Carroll
authors:
  - Ian Carroll

# Slides

slide_sorter:
  - intro
  - tiers
  - scrape
  - api
  - census
  - rdbms
  - conclude  

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
